version: "3"
services:
  app:
    build: .
    ports:
      - "80:80"
    container_name: flask_test
    env_file:
      - .env
    volumes:
      - ./:/app

  voicevox_engine:
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    ports:
      - "50021:50021"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]